### ISSUE TITLE
Use C++20 modules

### ISSUE THREAD

**Issue by ken-matsui** [poac-dev/poac#781]
#### TODO

- [x] Migrate sources to modules: https://github.com/poac-dev/poac/pull/776
- [ ] Migrate tests to modules
- [ ] Fix CIs somehow
- [ ] (opt) figure out how to publish to Homebrew

#### Ideal Roadmap

1. Use modules internally
2. Support git dependencies
3. Support building modules, i.e. build Poac itself

#### Steps

Currently cannot build tests.

```bash
export CXX=/opt/homebrew/opt/llvm/bin/clang++
cmake -B build -G Ninja -DPOAC_BUILD_TESTING=OFF
cd build
ninja
```

**Comment by ken-matsui** [comment]
Stop using C++20 modules, will use a different way to structure the project when I have time next.
